### ISSUE TITLE
Analysis Properties

### ISSUE THREAD

**Issue by monepic** [spotbugs/spotbugs-maven-plugin#113]
Hello,

Is there some way to set the [Analysis Properties](https://spotbugs.readthedocs.io/en/stable/analysisprops.html) when using the maven plugin?

Thank you

Ed

**Comment by hazendaz** [comment]
I'm not familiar with that aspect.  I sort of took this on more for my maven knowledge than for that of findbugs/spotbugs.  The code isn't super easy to read being all groovy but you might want to poke around the code and see.  If you don't see this anywhere, I'd be happy to review a pull request for support of the feature.

**Comment by acolomba** [comment]
Analysis properties are passed as Java system properties, so they can be set in the `<jvmArgs>` configuration element.

E.g. to set the `findbugs.assertionmethods` analyzer property:

```xml
<plugin>
    <groupId>com.github.spotbugs</groupId>
    <artifactId>spotbugs-maven-plugin</artifactId>
    <configuration>
        <jvmArgs>-Dfindbugs.assertionmethods=org.apache.commons.lang3.Validate.notNull</jvmArgs>
```

**Comment by hazendaz** [comment]
added this to readme, closing ticket. Thanks.
