### ISSUE TITLE
[Docs] The docs about the Spotbugs Maven plug-in contains broken links

### ISSUE THREAD

**Issue by SimonScholz** [spotbugs/spotbugs-maven-plugin#115]
Hi,

The links to the maven goals in https://github.com/spotbugs/spotbugs/blob/master/docs/maven.rst result in a 404.

**Comment by hazendaz** [comment]
@KengoTODA I figured out the issue.  The 'goal' was not being run that generates that piece.  I'll have a patch coming in shortly after I get upstream base parent updated due to another issue that popped up recently.

**Comment by hazendaz** [comment]
@KengoTODA Original issue was introduced long time ago prior to us taking this over.  See [here](https://github.com/spotbugs/spotbugs-maven-plugin/commit/0d34d0070d0d57720823039ca09f4c1bfb96ca3e#diff-600376dffeb79835ede4a0b285078036).  Effectively it added an execution that turned off part of the site generation needs.  I've ran tests with the full process and think that was purely a mistake.

**Comment by hazendaz** [comment]
Fixed.

**Comment by KengoTODA** [comment]
Great! Thanks!
