### ISSUE TITLE
Maven Site Goals Link 404

### ISSUE THREAD

**Issue by mttjj** [spotbugs/spotbugs-maven-plugin#120]
The [Goals](https://spotbugs.github.io/spotbugs-maven-plugin/plugin-info.html) link on the [Maven Site](https://spotbugs.github.io/spotbugs-maven-plugin/) leads to a 404. I couldn't find the information I was looking for by browsing through the git repo either. Makes it very hard to read up on the plugin! :)

**Comment by hazendaz** [comment]
I'll look into the issue.  It had been fixed on 3.1.12 release, not sure why snap shot is slowing again.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
issue is due to a bot behind the scenes that reverted the automatic changes already in place.  I'll work to get that removed in next few days.

**Comment by hazendaz** [comment]
This has been resolved now.
