### ISSUE TITLE
Using the -Dplugins parameter is useless in Linux

### ISSUE THREAD

**Issue by Orangelxl** [spotbugs/spotbugs-maven-plugin#127]
I used `mvn com.github.spotbugs:spotbugs-maven-plugin:spotbugs -Dplugin=com.h3xstream.findsecbugs:findsecbugs-plugin -DincludeFilterFile="spotbugs-security-include.xml" -DexcludeFilterFile="spotbugs-security-exclude.xml"` in Windows, that's OK.
But in Linux, it just used spotbugs, not findsecbugs-plugin, I don't know why

**Comment by hazendaz** [comment]
@Orangelxl Did you also try quotes around your usage as you did elsewhere?

**Comment by Orangelxl** [comment]
Oh, I found that I modified pom.xml on Windows but not on Linux. 
I want to automate code auditing through maven cli parameters rather than pom.xml.
I want use this `mvn com.github.spotbugs:spotbugs-maven-plugin:spotbugs -Dplugin=com.h3xstream.findsecbugs:findsecbugs-plugin -DincludeFilterFile="spotbugs-security-include.xml" -DexcludeFilterFile="spotbugs-security-exclude.xml"`
 After I tried it, I found that the spotbugs-maven-plugin's parameter settings didn't work. 
I had to modify pom.xml, but I didn't want to.

**Comment by Orangelxl** [comment]
Oh, I found that I modified pom.xml on Windows but not on Linux. 
I want to automate code auditing through maven cli parameters rather than pom.xml.
I want use this `mvn com.github.spotbugs:spotbugs-maven-plugin:spotbugs -Dplugin=com.h3xstream.findsecbugs:findsecbugs-plugin -DincludeFilterFile="spotbugs-security-include.xml" -DexcludeFilterFile="spotbugs-security-exclude.xml"`
 After I tried it, I found that the spotbugs-maven-plugin's parameter settings didn't work. 
I had to modify pom.xml, but I didn't want to.

**Comment by hazendaz** [comment]
@Orangelxl I understand now.  Currently there are two ways to get plugins added.  You figured out the inbuilt one in the pom.  The other is pluginList.  However that requires you to physically provide the jar including path so it can pass that onto spotbugs.  I think to accomplish the nicer looking setup approach you have, you may want to invest some time trying to work out the details and raise a pull request.  The area of code you will want to look at in its current handling is in the SpotBugsPluginsTrait.groovy class.

**Comment by hazendaz** [comment]
work around was noted, no follow up, closing.
