### ISSUE TITLE
Allow spotbugs maven plugin to produce xml AND html

### ISSUE THREAD

**Issue by planetf1** [spotbugs/spotbugs-maven-plugin#150]
Currently the spotbugs maven plugin can be configured to produce EITHER xml or html.

In our build for https://github.com/odpi/egeria we are running spotbugs (with find-secbugs) & creating .xml files which are then uploaded to SonarCloud for incorporation in with the output from pmd and sonar's own scans.

For developers & other interested parties, viewing the spotbugs output alone would be useful - ie by producing .html files in the build output tree per-component.

The plugin doesn't currently allow this. Enabling dual output would be useful, or an additional goal to format the .xml into .html . Or even adding documentation as to how to process the .xml files into a more human readable form

**Comment by hazendaz** [comment]
Resolved now as part of #161.  Will be released within the week.
