### ISSUE TITLE
Introduce threshold of warnings before failing

### ISSUE THREAD

**Issue by Serranya** [spotbugs/spotbugs-maven-plugin#184]
Currently we often have the following use case.

We add spotbugs to a new project. Spotbugs shows a few hundred warnings. We see way to many problems to fix in a few days/weeks. But we still want to incrementally improve the code base.

Currently we just need to look very carefully at the number of warnings to make sure that the situation improves. This is not optimal.

What I would like would be something like this in my pom.xml
```xml
<spotbugs.failOnError>true</spotbugs.failOnError>
<spotbugs.failThreshold>200</spotbugs.failThreshold>
```
the build should fail if there are more than spotbugs.failThreshold problems. This way we could decrease the number in every sprint by a little and incrementally improve the code while also making sure that new commits don't add new problems.

**Comment by hazendaz** [comment]
Would you be able to raise a pull request for this?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Serranya** [comment]
Yes probably.

**Comment by Serranya** [comment]
I just took a look at the source and there seems already to be a maxAllowedViolations. This would fit my requirements :)

I don't know how I missed this parameter the first time I looked.

**Comment by hazendaz** [comment]
OK cool.  Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
