### ISSUE TITLE
4.0.0 changelog is missing

### ISSUE THREAD

**Issue by oleg-nenashev** [spotbugs/spotbugs-maven-plugin#197]
Hi, it looks like 4.0.0 major release was cut 2 days ago, and so far there is release notes associated with it (AFAICT).

- No changelog on Gitub Releases: https://github.com/spotbugs/spotbugs-maven-plugin/releases/tag/spotbugs-maven-plugin-4.0.0
- GitHub.io site references 4.0.0-SNAPSHOT which does not seem to be complete: https://spotbugs.github.io/spotbugs-maven-plugin/changelog.html

Diff between versions is quite long: https://github.com/spotbugs/spotbugs-maven-plugin/compare/spotbugs-maven-plugin-3.1.12.2...spotbugs-maven-plugin-4.0.0 . It would be great to have official release notes and, especially, the compatibility notice with a summary of breaking changes

**Comment by jjlharrison** [comment]
There are release notes: https://github.com/spotbugs/spotbugs/blob/master/CHANGELOG.md#400---2020-02-15

**Comment by hazendaz** [comment]
I'll add a note but yah its just to support spot bugs 4.0.  Everything else is mostly build related.  There are maybe a handful of improvements.  I'll try to get something up today.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
change log added.  Nothing specific in relation to spotbugs directly.
