### ISSUE TITLE
Release 4.1.3?

### ISSUE THREAD

**Issue by famod** [spotbugs/spotbugs-maven-plugin#259]
It's been a while since 4.0.4 and SB itself is already on 4.1.3.
I am also "waiting" for https://github.com/spotbugs/spotbugs-maven-plugin/commit/973fb04f5e02a0dc80b4d532dfa4448556c28ec2

I'd therefore appreciate a new release of the plugin (4.1.3?).

**Comment by hazendaz** [comment]
I'll try to get the release out tomorrow.

**Comment by hazendaz** [comment]
Resolved, this will be in central in next 2 hours.

**Comment by famod** [comment]
Awesome, thanks @hazendaz!
