### ISSUE TITLE
Maven central has v3.1.1, but source has 3.1.1-SNAPSHOT

### ISSUE THREAD

**Issue by lkamal** [spotbugs/spotbugs-maven-plugin#26]
It seems there is a confusion in this plugins version number.

pom.xml has 3.1.1-SNAPSHOT version as below.

`<version>3.1.1-SNAPSHOT</version>`

Maven central has [3.1.1 release](https://mvnrepository.com/artifact/com.github.spotbugs/spotbugs-maven-plugin/3.1.1).

    <dependency>
        <groupId>com.github.spotbugs</groupId>
        <artifactId>spotbugs-maven-plugin</artifactId>
        <version>3.1.1</version>
    </dependency>
`

**Comment by lkamal** [comment]
I looked at the [releases](https://github.com/spotbugs/spotbugs-maven-plugin/releases) and [tags](https://github.com/spotbugs/spotbugs-maven-plugin/tags) of the plugin, but none has a release version 3.1.1.

How come maven central has a release numbered 3.1.1?

**Comment by hazendaz** [comment]
@lkamal Thanks for reporting. This has been corrected.  The artifacts (tag and commits) didn't come off my machine properly.  I suspect related to being attached to 4 different remotes.  I will research that some more but now everything is there.
