### ISSUE TITLE
Duplicate paragraph in maven site documentation

### ISSUE THREAD

**Issue by Bananeweizen** [spotbugs/spotbugs-maven-plugin#266]
https://spotbugs.github.io/spotbugs-maven-plugin/usage.html

Paragraphs 3 and 4 are identical (except for their headline):
* Filter bugs to report
* Specifying which bug filters to run

**Comment by hazendaz** [comment]
@Bananeweizen Can you raise a Pull Request for this issue?

**Comment by hazendaz** [comment]
resolved.  closing.
