### ISSUE TITLE
Provide 4.1.4 release?

### ISSUE THREAD

**Issue by iloveeclipse** [spotbugs/spotbugs-maven-plugin#269]
See discussion in https://github.com/spotbugs/spotbugs/issues/1340.
Should we create 4.1.4 release?

**Comment by hazendaz** [comment]
sure, not necessary but can push the update today.

**Comment by hazendaz** [comment]
released, will be in central in next couple hours.

**Comment by iloveeclipse** [comment]
Thanks! It would be nice to keep the plugin in-sync with spotbugs.
