### ISSUE TITLE
false positive RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE on try-with-resource with Java 11

### ISSUE THREAD

**Issue by mofleury** [spotbugs/spotbugs-maven-plugin#271]
Hi,

I am facing an issue that seems to be a false positive, and that appears when compiling in Java 11, using Low threshold.

It seems to impact try-with-resources, when more than one instance are created. The error I receive is RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE. It affects at least versions 4.1.4 and 4.1.3.

Here is a minimal reproduction case : 

source code : 
```java
import java.io.FileInputStream;
import java.io.IOException;
import java.nio.channels.FileChannel;

public class SpotBug {

	public void testCase(String finalFile, String tempFile) throws IOException {

		try (FileInputStream fileInputStream = new FileInputStream(finalFile);
				FileChannel src = fileInputStream.getChannel()) {
			System.out.println("got a file channel : " + src);
		}
	}

}
```

pom.xml : 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>org.example</groupId>
	<artifactId>spotbugs-repro</artifactId>
	<version>1.0.0-SNAPSHOT</version>

	<properties>

	</properties>

	<build>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.0</version>
				<configuration>
					<source>11</source>
					<target>11</target>
				</configuration>
			</plugin>


			<plugin>
				<groupId>com.github.spotbugs</groupId>
				<artifactId>spotbugs-maven-plugin</artifactId>
				<version>4.1.4</version>

				<configuration>
					<threshold>Low</threshold>
				</configuration>
			</plugin>

		</plugins>
	</build>
</project>
```

when executing ` mvn clean install && mvn spotbugs:check` , I get the following error : 
```
[ERROR] Low: Redundant nullcheck of src, which is known to be non-null in org.example.SpotBug.testCase(String, String) [org.example.SpotBug] Redundant null check at SpotBug.java:[line 11] RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE
```

Can you please look into this issue? My current workaround is to disable the rule completely, which is not ideal.

Thank you!

Marc-Olivier Fleury

**Comment by mofleury** [comment]
side note : this bug does not appear with Java 8, I have not tested with 9 or 10.

**Comment by hazendaz** [comment]
It sounds like the issue is with spotbugs itself rather than the plugin.  Have you checked to see if this is reported on spotbugs?  The plugin is just wrapping spotbugs.

**Comment by mofleury** [comment]
ah yes, should be an issue for spotbugs itself, you are right. I'll check this with them and report it there if not done already.

Thank you!

**Comment by mofleury** [comment]
Yes indeed, it was reported here : https://github.com/spotbugs/spotbugs/issues/1338

Closing this one then!
