### ISSUE TITLE
GitHub Pages (gh-pages) broken

### ISSUE THREAD

**Issue by joschi** [spotbugs/spotbugs-maven-plugin#298]
The website for `spotbugs-maven-plugin` seems to be broken since 05eb4f71bad7d44732229f527ec697e2d7117869 (on `gh-pages` branch).

The documentation at https://spotbugs.readthedocs.io/en/latest/maven.html links to https://spotbugs.github.io/spotbugs-maven-plugin/ which is "empty".

```
$ curl -I https://spotbugs.github.io/spotbugs-maven-plugin/
HTTP/2 404
content-type: text/html; charset=utf-8
server: GitHub.com
x-origin-cache: HIT
access-control-allow-origin: *
etag: "5f5fee10-247b"
content-security-policy: default-src 'none'; style-src 'unsafe-inline'; img-src data:; connect-src 'self'
x-proxy-cache: MISS
x-github-request-id: DCC0:E7D1:394383C:3D457A4:5FF47E93
accept-ranges: bytes
date: Tue, 05 Jan 2021 14:58:32 GMT
via: 1.1 varnish
age: 5
x-served-by: cache-hhn4080-HHN
x-cache: HIT
x-cache-hits: 1
x-timer: S1609858712.257489,VS0,VE1
vary: Accept-Encoding
x-fastly-request-id: b857778314adff665deaa2b2a82050197586ebfe
content-length: 9339
```

**Comment by hazendaz** [comment]
@joschi Thanks.  I saw that then it appeared again so something in the switch over from the old way to github actions.  I'm looking into it now.

**Comment by hazendaz** [comment]
@joschi Site is back up.  Odd issue.  I moved from a long unsupported site deployment to the way maven scm is doing it natively now.  This project uses a super pom for most of its setup and it seems it detected that making it go back 2 directories then resolved oddly named directory.  Anyway, was able to just use that location as it was in the build still.  So all back to working order.
