### ISSUE TITLE
upgade from 3.0.X to 3.1.1 that demands maven upgrade to 3.5.2

### ISSUE THREAD

**Issue by romani** [spotbugs/spotbugs-maven-plugin#30]
Is there a good reason to stick with most recent 3.5.2 maven core ?
https://github.com/spotbugs/spotbugs-maven-plugin/commit/765a70a12c081e5a5a76ae6112a0eb8d6bbff628

can it be some lowered to 3.2 version or even below 3.2 ?

Upgrade to new version is very complicated, 
see details at https://github.com/checkstyle/checkstyle/issues/5525 , I would say in our case , it is impossible to upgrade.

**Comment by hazendaz** [comment]
@romani based on that commit there is probably no real good reason to stick on the maven core 3.5.2.  I need to go back though and confirm why I did that to start with.  This issue has been noted now a couple of times.  I'm guessing this might have had something to do with jdk9 compatibility but need to go back over my tracks on that.  If it is as simple as backing that out and there are no other related issues, I can go ahead and back that out.

**Comment by hazendaz** [comment]
@romani It does not appear that I did that due to any specific need other than aligning all maven usage on 3.5.2.  Are you able to test against snapshots?  I'd like to get a confirmation this solves the backwards compatibility issues before I cut a release.

**Comment by romani** [comment]
> Are you able to test against snapshots?

I have problems to reproduce a problem on my local, it hapens on only on remote CIs. But build is easy to update to use snapshot - just change a version and run "mvn verify"

**Comment by hazendaz** [comment]
I've got a test working back to maven 3.1.1.  It's harder to go any further base so I'm going to make that the minimum allowed with spotbugs then I'll push a release either later tonight or sometime tomorrow.

**Comment by hazendaz** [comment]
Version 3.1.2 released fixing this issue.

**Comment by romani** [comment]
hmm, It does not help, see logs at failed CIs: https://github.com/checkstyle/checkstyle/pull/5540

**Comment by lpapazow** [comment]
The new release didn't solve the issue for me either.

 I started checking out older commits and I found that the problems start after [this commit](https://github.com/spotbugs/spotbugs-maven-plugin/commit/d538fb53c25518ab756f1d9edcfa955d569fea24) . 
Changing the `mavenVersion` property in the pom from 3.5.2 to 3.5.0 in the latest commit worked for me though.

**Comment by romani** [comment]
@hazendaz , does it make sense to reopen issue ?

**Comment by hazendaz** [comment]
@romani 
Can you give me a bit more insight into the error you had?  All I could see was one failure and that did not look applicible to this plugin but rather something with the install plugin.

@lpapazow What error did you get?

**Comment by romani** [comment]
> Can you give me a bit more insight into the error you had?

do you need full log ? or .... let me know details you need.

**Comment by hazendaz** [comment]
Just details will help.  I couldn't see everything and the only one I could looked like the install plugin had issues.  Was the issue different from the one you originally experienced?  I have a few ideas on how I might deal with issue such as making maven provided scope instead but not sure that will work but something I'm going to try.  The idea being that maybe that might make it work on prior versions or new version since the libraries are present.  But first, I'm trying to determine how I can test and get the failure.

**Comment by romani** [comment]
I created new PR, to regenerate logs, I will copy them for you in gist for review.
I still can not reproduce problem on my local, so I have failures only on remotes.

**Comment by hazendaz** [comment]
Same issue I have.  Thanks!

**Comment by lpapazow** [comment]
I get the same error. I can upload the full error log in a gist if you think it could help.

**Comment by romani** [comment]
diff for checkstyle project:
```
-    <maven.spotbugs.plugin.version>3.1.0-RC8</maven.spotbugs.plugin.version>
+    <maven.spotbugs.plugin.version>3.1.1</maven.spotbugs.plugin.version>
```

full build logs:
distelli - https://gist.github.com/romani/1b0f4954bc659179afe70f4afde4c33b
circle - https://gist.github.com/romani/ea5864b13a3cba2ff43e34b3abda76ba
teamcity - https://gist.github.com/romani/f56b79d6e394b7efe3110dac644005d8

**Comment by hazendaz** [comment]
version 3.1.3 has been released, can you please give that a try and see if it solves the problem?

**Comment by romani** [comment]
new PR is created  - https://github.com/checkstyle/checkstyle/pull/5579

**Comment by romani** [comment]
it works for our CI, thanks a lot.

**Comment by hazendaz** [comment]
Awesome!  Thanks for hanging in there on this one!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
