### ISSUE TITLE
Please push the sources that were used for 4.2.2 release (available in central)

### ISSUE THREAD

**Issue by pzygielo** [spotbugs/spotbugs-maven-plugin#308]
I understand sources are distributed in https://repo.maven.apache.org/maven2/com/github/spotbugs/spotbugs-maven-plugin/4.2.2/ `*-sources.jar` as usual, but it would be nice for them to be synchronized with repository.

If possible - please push the tag as well.

**Comment by hazendaz** [comment]
tag pushed, not sure what you mean with sources, those are as released as its all pushed at once.

**Comment by hazendaz** [comment]
assuming you were referring to exact commits as like tags were not pushed.  both are up now.  closing this out.

**Comment by pzygielo** [comment]
Yes, those commits I meant - thank you!

**Comment by hazendaz** [comment]
I opened a separate ticket so I remember to turn those on by default.  That is a hold over from original ownership and not normal in most things I work on anyways so its easily missed.
