### ISSUE TITLE
Spring CSRF protection disabled

### ISSUE THREAD

**Issue by wellmsan** [spotbugs/spotbugs-maven-plugin#330]
Hi Guys! 

Spotbugs does not allow CSRF disabled in Spring Secutiry settings.
```
@Override
    protected void configure(HttpSecurity http) throws Exception {
        http.csrf().disable();
    }
```
How do I disregard this validation? I need to keep the CRSF incapacitated.

**Comment by h3xstream** [comment]
This is a question that is related to https://github.com/find-sec-bugs/find-sec-bugs/issues

**Comment by hazendaz** [comment]
closing as solution noted.
