### ISSUE TITLE
spotbugs or findsecbugs create directory in target which it shouldnt

### ISSUE THREAD

**Issue by nimaj94** [spotbugs/spotbugs-maven-plugin#34]
I am currently using spotbugs and i use it using maven, so i put these lines in my pom in reporting plugins

```xml

<plugin>
<groupId>com.github.spotbugs</groupId>
  <artifactId>spotbugs-maven-plugin</artifactId>
  <version>3.1.1</version>
<configuration>
<plugins>
<plugin>
<groupId>com.h3xstream.findsecbugs</groupId>
<artifactId>findsecbugs-plugin</artifactId>
<version>LATEST</version>
<!-- Auto-update to the latest stable -->
</plugin>
</plugins>
</configuration>
</plugin>
```

but there is a problem.
when i execute site:site it create some directory inside my target folder.
 the directory is
C_\Users\ [myUserName] \ .m2\repository\com\h3xstream\findsecbugs\findsecbugs-plugin\1.7.1
 and findsecbugs-plugin-1.7.1.jar is inside this directory.
like it should be 
 C:\Users\ [myUserName] \ .m2\repository\com\h3xstream\findsecbugs\findsecbugs-plugin\1.7.1
but somebody accidentally use '_' instead of ':' .

**Comment by hazendaz** [comment]
spotbugs creates this due to underlying groovy usage.  I'm unsure how to fix it but see the issue is duplicating files all over.

**Comment by hazendaz** [comment]
This original issue was handling that was missing with windows that was present for linux style line endings.  The original fix put in actually broke things so this is sort of an issue still.  I think copying the jars to target is unnecessary as they won't change during the run  However, for time being to get folks running again the original issue here of deeply nested is gone.  The jar files in question will still be added to target.  Opening new issue and will flag it back to this.
