### ISSUE TITLE
Could you consider creating a GitHub Releases page for each tag?

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/spotbugs-maven-plugin#359]
Currently GitHub's UI displays the version 4.2.0 as latest:

![IMG_20210922_083255](https://user-images.githubusercontent.com/505751/134265160-6146d75e-64e3-4e41-8ab9-d5b18513e650.jpg)

This is because we have no GitHub Releases page for the version 4.2.2 and later.

We can automate the Releases page creation. If we use `mvn release:perform` to deploy artifacts, we can hook the tag event and run GitHub CLI or hub command. Here is living example from spotbugs core:

https://github.com/spotbugs/spotbugs/blob/26c19193d7d0fbb69d115431dfbf2996881f8716/.github/workflows/release.yml

Thanks for reading this issue!

**Comment by KengoTODA** [comment]
In the Releases page, it is nice to provide changelog or release note, but it depends on project.

**Comment by hazendaz** [comment]
@KengoTODA I'll look into doing so.  Might look at what maven recently did with some plugins, they setup auto changelog creation and that probably can assist here.  What line specifically in the attached am I looking at?  I looked at it but wans't sure exactly what was pushing the release log there.  Not a big deal, I'm sure there is a specific action for it that makes it easier in the process.  Currently I do the release manually using maven release but could automate that entirely (at some point).

**Comment by hazendaz** [comment]
Going to close for now.  I don't quite like how spotbugs does this as it seems chicken and egg in that PR has commits but no tag and push has to occur.  I'm planning on looking into a better model where code is simply merged to release/x.x.x where x.x.x is the version string to release and the process takes care of that so it will be quite different then gradle usage.  I'll be doing that on mybatis projects when I have time to figure that out and will apply same here after.  In meantime, I'm pretty comfortable of getting release notes most often now before I even let it out of staging.  Ultimately yes I want it automated as everything at volume is becoming too time consuming.
