### ISSUE TITLE
Parent Pom not importing correctly

### ISSUE THREAD

**Issue by neodem** [spotbugs/spotbugs-maven-plugin#367]
Our company uses Jfrog Artifactory for a maven repo and it is having trouble when importing the plugin.

It appears that the parent pom : https://github.com/spotbugs/spotbugs-maven-plugin/blob/2b57e82ca7c5eadcde1f4479436ef53a1317f685/pom.xml#L6

is not able to be read because of references to: `child.project.url.inherit.append.path`

Would if be possible to clean this reference out of the parent pom, or better yet, remove the parent pom entirely?

**Comment by hazendaz** [comment]
@neodem I'm in process of releasing a new copy with removal of those attributes so you can get around this.  Given this is second report of same issue and knowing most corporate policy would not allow you to get around this in a timely manor and the fact that maven failed to document this well and it doesn't do as advertised anyways, it fealt best to just remove that logic.  Expect new version 4.4.2.2 to be available later today.

**Comment by neodem** [comment]
Thank you so much for this. You're right, getting my company to upgrade Artifactory in a timely way is a giant undertaking!

This worked. Thank you for the repair.

I did get a Java warning (java 17) when running though. I suppose you know about this already though..

```
     [java] WARNING: A terminally deprecated method in java.lang.System has been called
     [java] WARNING: System::setSecurityManager has been called by edu.umd.cs.findbugs.ba.jsr305.TypeQualifierValue (file:/Users/vfumo000/.m2/repository/com/github/spotbugs/spotbugs/4.4.2/spotbugs-4.4.2.jar)
     [java] WARNING: Please consider reporting this to the maintainers of edu.umd.cs.findbugs.ba.jsr305.TypeQualifierValue
     [java] WARNING: System::setSecurityManager will be removed in a future release
```

**Comment by hazendaz** [comment]
closing as original issue resolved for older artifactory.
