### ISSUE TITLE
Warning about deprecated options -output and -outputFile

### ISSUE THREAD

**Issue by radio-rogal** [spotbugs/spotbugs-maven-plugin#369]
Full text:

> [INFO] >>> spotbugs-maven-plugin:4.5.0.0:check (default-cli) > :spotbugs @ project-name >>>
> [INFO] 
> [INFO] --- spotbugs-maven-plugin:4.5.0.0:spotbugs (spotbugs) @ project-name ---
> [INFO] Fork Value is true
>      **[java] [main] WARN edu.umd.cs.findbugs.TextUICommandLine - -output option and -outputFile option are deprecated. Set file path to each option for reporter.**
> [INFO] Done SpotBugs Analysis....

I have run just `mvn spotbugs:check`

**Comment by hazendaz** [comment]
@radio-rogal Once PR #382 is merged, can you confirm 'spotbugs' branch here now works as you expect?

**Comment by radio-rogal** [comment]
Confirm that the warning message is not shown:

    [INFO] >>> spotbugs-maven-plugin:4.5.2.0-SNAPSHOT:check (default-cli) > :spotbugs @ project-name >>>
    [INFO] 
    [INFO] --- spotbugs-maven-plugin:4.5.2.0-SNAPSHOT:spotbugs (spotbugs) @ project-name ---
    Downloading from central: https://repo.maven.apache.org/maven2/com/github/spotbugs/spotbugs-annotations/4.5.2/spotbugs-annotations-4.5.2.jar
    Downloaded from central: https://repo.maven.apache.org/maven2/com/github/spotbugs/spotbugs-annotations/4.5.2/spotbugs-annotations-4.5.2.jar (15 kB at 31 kB/s)
    [INFO] Fork Value is true
    [INFO] Done SpotBugs Analysis....
    [INFO] 
    [INFO] <<< spotbugs-maven-plugin:4.5.2.0-SNAPSHOT:check (default-cli) < :spotbugs @ project-name <<<
    [INFO] 
    [INFO] 
    [INFO] --- spotbugs-maven-plugin:4.5.2.0-SNAPSHOT:check (default-cli) @ project-name ---
    [INFO] BugInstance size is 0
    [INFO] Error size is 0
    [INFO] No errors/warnings found

**Comment by hazendaz** [comment]
@radio-rogal Great!  Thank you!  I'll push this release out today.
