### ISSUE TITLE
documentation: goals

### ISSUE THREAD

**Issue by Reissner** [spotbugs/spotbugs-maven-plugin#374]
I needed some time to spot the goas: 
I found https://spotbugs.readthedocs.io/en/stable/maven.html. 
Better this is written down for the maven plugin also.

**Comment by hazendaz** [comment]
That is the maven plugin, not sure what the ask is here.  and actual IO pages for the plugin have all goals listed as that is how maven works -> https://spotbugs.github.io/spotbugs-maven-plugin/plugin-info.html.

**Comment by hazendaz** [comment]
closing as this is documented on readme.
