### ISSUE TITLE
Don't output to INFO, but to WARN or ERROR instead

### ISSUE THREAD

**Issue by sco0ter** [spotbugs/spotbugs-maven-plugin#38]
When running `mvn spotbugs:check` it outputs all bugs to INFO:

```
[INFO] Private method ...
UPM_UNCALLED_PRIVATE_METHOD
```

This hardly catches one's attention.
Maven 3.5 supports colorizing output and prints warnings in yellow and errors in red.

I suggest to print bugs as those (warn or errors), so that developers more easily sees them in Maven output. Especially useful if not failing the build (`<failOnError>false</failOnError>`)

**Comment by hazendaz** [comment]
@sco0ter I ran both warning and error.  I like error better for attention grabbing red.  I'll push a patch shortly.
