### ISSUE TITLE
Java 9 Illegal reflective access groovy 2.4.13

### ISSUE THREAD

**Issue by hheg** [spotbugs/spotbugs-maven-plugin#46]
`[INFO] --- spotbugs-maven-plugin:3.1.1:spotbugs (spotbugs) @ project ---
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/home/hheg/.m2/repository/org/codehaus/groovy/groovy/2.4.13/groovy-2.4.13.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] 
[INFO] <<< spotbugs-maven-plugin:3.1.1:check (default) < :spotbugs @ project <<<
[INFO] `

The project is a parent and of a pom type.

This error is probably related to https://issues.apache.org/jira/browse/GROOVY-8339

From spotbugs/spotbugs#598

**Comment by hazendaz** [comment]
Closing issue as this is not a problem with our library.  Groovy is aware of the issue and it is not fixed in any of their versions includuing 2.5, 2.6, and 3.0 releases.  There is no need for us to track their issue.  We are otherwise good through jdk10.

**Comment by electrum** [comment]
We should be able to fix this when when using `<fork>true</fork>` by adding the appropriate `--add-opens` arguments for the forked JVM. I did something similar for a Maven plugin that uses Jython: https://github.com/airlift/sphinx-maven-plugin/commit/c870da4b6436fe75d0e71dbd3a9ff079793d3927

**Comment by hazendaz** [comment]
Groovy long since fixed issues.  We are no longer having any problems I'm aware of.  We run fine on all jdk version now.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by electrum** [comment]
I still see this error with version `3.1.10` of the plugin. It actually happens during configuration, even if the plugin is disabled with `<skip>true</skip>`:
```
[INFO] --- spotbugs-maven-plugin:3.1.10:spotbugs (spotbugs) @ presto-spi ---
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/Users/dphillips/.m2/repository/org/codehaus/groovy/groovy/2.5.4/groovy-2.5.4.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] 
[INFO] <<< spotbugs-maven-plugin:3.1.10:check (default-cli) < :spotbugs @ presto-spi <<<
```

**Comment by electrum** [comment]
Ah, I see that the plugin itself is written in Groovy (rather than embedding it), which explains why it happens even when disabled, so the suggested workaround isn't an option.

**Comment by hazendaz** [comment]
Yes but that is a warning originating in third party.  I have zero plans to hide the warning.  That does nothing to fix it.  As it stated, report to owner of the library in question.  This plugin isnt the issue.  Groovy is.  They are aware anyways and it will eventually be fixed.  Until then there is no issue here.

Just caught your last message.  You got it! Thanks!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bentatham** [comment]
For those curious to follow and/or vote for the root issue:
https://issues.apache.org/jira/browse/GROOVY-8339
