### ISSUE TITLE
Extraneous "following classes needed for analysis were missing" message introduced in 4.7.3.1?

### ISSUE THREAD

**Issue by davewichers** [spotbugs/spotbugs-maven-plugin#551]
Upgrading from 4.7.3.0 to 4.7.3.1 fixed the Doxia issue with the new maven site plugin. Thanks for that. However, I see all this extra output now that wasn't there before when using this on AntiSamy:

     [java] The following classes needed for analysis were missing:
     [java]   org.apache.batik.css.parser.Parser
     [java]   org.w3c.css.sac.DocumentHandler
     [java]   org.apache.hc.core5.http.io.HttpClientResponseHandler
     [java]   org.apache.xml.serialize.HTMLSerializer
     [java]   net.sourceforge.htmlunit.cyberneko.filters.DefaultFilter
     [java]   net.sourceforge.htmlunit.xerces.xni.parser.XMLDocumentFilter
     [java]   net.sourceforge.htmlunit.xerces.dom.DocumentImpl
     [java]   net.sourceforge.htmlunit.cyberneko.parsers.DOMFragmentParser
     [java]   org.apache.batik.css.parser.Scanner
     [java]   org.w3c.css.sac.CSSParseException
     [java]   net.sourceforge.htmlunit.cyberneko.parsers.SAXParser
     [java]   org.apache.hc.core5.http.HttpEntity
     [java]   org.apache.hc.core5.http.ClassicHttpResponse
     [java]   org.apache.hc.core5.http.io.entity.EntityUtils
     [java]   org.apache.hc.client5.http.ClientProtocolException
     [java]   org.apache.hc.core5.util.Timeout
     [java]   org.apache.hc.client5.http.config.RequestConfig
     [java]   org.apache.hc.core5.http.ClassicHttpRequest
     [java]   org.slf4j.Logger
     [java]   org.w3c.css.sac.InputSource
     [java]   org.apache.hc.client5.http.config.RequestConfig$Builder
     [java]   org.apache.hc.client5.http.impl.classic.HttpClientBuilder
     [java]   org.apache.hc.client5.http.classic.methods.HttpGet
     [java]   org.apache.hc.client5.http.classic.HttpClient
     [java]   org.slf4j.LoggerFactory
     [java]   org.apache.xml.serialize.OutputFormat
     [java]   net.sourceforge.htmlunit.xerces.xni.QName
     [java]   net.sourceforge.htmlunit.xerces.xni.XMLString
     [java]   net.sourceforge.htmlunit.xerces.xni.Augmentations
     [java]   net.sourceforge.htmlunit.xerces.xni.XMLAttributes
     [java]   net.sourceforge.htmlunit.xerces.util.XMLStringBuffer
     [java]   net.sourceforge.htmlunit.xerces.util.AugmentationsImpl
     [java]   net.sourceforge.htmlunit.xerces.util.XMLAttributesImpl
     [java]   org.apache.xml.serialize.ElementState
     [java]   org.apache.xml.serialize.Printer
     [java]   org.apache.xml.serialize.HTMLdtd
     [java]   org.w3c.css.sac.LexicalUnit
     [java]   org.w3c.css.sac.Selector
     [java]   org.w3c.css.sac.SimpleSelector
     [java]   org.w3c.css.sac.Condition
     [java]   org.w3c.css.sac.AttributeCondition
     [java]   org.w3c.css.sac.DescendantSelector
     [java]   org.w3c.css.sac.ConditionalSelector
     [java]   org.w3c.css.sac.SiblingSelector
     [java]   org.w3c.css.sac.CombinatorCondition
     [java]   org.w3c.css.sac.NegativeCondition
     [java]   org.w3c.css.sac.SACMediaList
     [java]   org.w3c.css.sac.SelectorList
     [java]   org.apache.batik.css.parser.ParseException
     [java]   org.apache.hc.core5.http.HttpStatus
     [java]   org.apache.hc.core5.http.ParseException
     [java]   org.apache.hc.core5.http.HttpException
     [java]   org.apache.batik.css.parser.LexicalUnits
     [java]   org.w3c.css.sac.CSSException
     [java]   org.w3c.css.sac.NegativeSelector
     [java]   net.sourceforge.htmlunit.xerces.xni.XNIException
[INFO] Done SpotBugs Analysis....

Was this change on purpose or is this a bug? I'm pretty sure these are all imported via the project's pom or it wouldn't even work.

**Comment by hazendaz** [comment]
@davewichers Fix in the works...

**Comment by hazendaz** [comment]
I reviewed all our IT tests and nothing exposed this.  So I'm writing some tests to expose the condition so we can ensure this does not happen in future.  This was the aux path changes that are now fixed.  Will have release out as soon as I've finished more testing.

**Comment by davewichers** [comment]
@hazendaz - Thanks for the quick fix! I tested it on AntiSamy. Looks good.
