### ISSUE TITLE
Generate HTML Report with Findbugs

### ISSUE THREAD

**Issue by SimonScholz** [spotbugs/spotbugs-maven-plugin#60]
I am pretty sure that with findbugs it was possible to generate html reports during a maven build.
Is there a way to generate a more human readable output during the build?

**Comment by vogella** [comment]
+1 for the ability to generate HTML reports out of the box.

**Comment by kennardconsulting** [comment]
+1

This is actually pretty important from a Project Management perspective. We have departments that require us to submit a written report of the analysis.

**Comment by hazendaz** [comment]
It already does this.  Run mvn site.   Am I missing something here?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MirPing** [comment]
how can i generate html output with maven findbugs plugin?

**Comment by kennardconsulting** [comment]
@hazendaz yes you are correct. `mvn site` does it

**Comment by cziesman** [comment]
We would like to generate the report as part of the Maven verify phase, so that developers have access to it when a Jenkins build fails due to too many errors. How do we achieve this? We do not use mvn site in our CI/CD pipeline because it takes too long to complete.

**Comment by hazendaz** [comment]
@cziesman How do you plan to make the site html pages available during that run?  Generally you just have the jenkins console output available to the users.  There as with many other plugins, it will show you where the issues are when using 'spotbugs:check'.

**Comment by jcamerin** [comment]
Developers on my regularly ask how to check static analysis locally on their development machines.  If the plugin can generate html output, they will be able to open those pages with a browser.  This is faster for them than waiting for a Jenkins build to complete

**Comment by NeelimaShrm** [comment]
Can we now generate HTML report or feature is still not released for end users? If yes, please share the configuration needed.

**Comment by hazendaz** [comment]
feature was never completed and is still sitting outstanding #161

**Comment by hazendaz** [comment]
This has now been worked on and merged into spotbugs branch.  Will release within the week.
