### ISSUE TITLE
Update to spotbugs 3.1.4 and release spotbugs-maven-plugin v3.1.4

### ISSUE THREAD

**Issue by hoerup** [spotbugs/spotbugs-maven-plugin#62]
spotbugs is released in v3.1.4 so it would be nice to have the corresponding spotbugs-maven-plugin version.

**Comment by PascalSchumacher** [comment]
Spotbugs 3.1.4 works on Java 11. If I override the Spotbugs version used by spotbugs-maven-plugin it works on Java 11.

Therefore a 3.1.4 release would be great.

**Comment by hazendaz** [comment]
This is pending upstream fixes.  Spotbugs removed a method that we need due to a downstream test with findsecbugs.  It's been added back but waiting to see if that will be released.

**Comment by KengoTODA** [comment]
Please wait 3.1.5, because 3.1.4 has compatibility problem.
https://github.com/spotbugs/spotbugs/issues/661

**Comment by hazendaz** [comment]
@hoerup @PascalSchumacher Version 3.1.5 has been released.

**Comment by PascalSchumacher** [comment]
Thank you very much!
