### ISSUE TITLE
lifecycle-mapping-metadata.xml should contain goal of spotbugs-maven-plugin

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/spotbugs-maven-plugin#68]
At [here](https://github.com/spotbugs/spotbugs-maven-plugin/blob/spotbugs-maven-plugin-3.1.5/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml#L6
) we have `<goal>compile</goal>`. The `compile` is not goal of our plugin but phase in Maven lifecycle. It should be `<goal>check</goal>` to run SpotBugs plugin at the timing to build.

refs https://www.eclipse.org/m2e/documentation/m2e-making-maven-plugins-compat.html

**Comment by KengoTODA** [comment]
I'm not sure this fix is enough to link maven-spotbugs-plugin with m2e. Maybe we need some additional bridge to report detected issues in editor?

**Comment by hazendaz** [comment]
I think that is likely enough.  I've had luck with other plugins by defining that myself in super pom in other cases.  At the very least, can you raise a PR to fix the issue?

**Comment by KengoTODA** [comment]
YES I will.

**Comment by hazendaz** [comment]
Fixed by #69.  I don't think there is any need for anything more with m2e.

**Comment by hazendaz** [comment]
Sorry, reopening.  I thought this had been merged.
