### ISSUE TITLE
Update Continuous Integration to test against Java 11 

### ISSUE THREAD

**Issue by vimal4david** [spotbugs/spotbugs-maven-plugin#78]

**Comment by hazendaz** [comment]
Are you referring to travis city? Jdk 11 won't work until groovy updates asm.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by vimal4david** [comment]
Build details: https://travis-ci.org/spotbugs/spotbugs-maven-plugin/jobs/429572630
As mentioned by @hazendaz it's failing with JDK 11 

[ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.6.1:generateStubs (compileGroovy) on project spotbugs-maven-plugin: Error occurred while calling a method on a Groovy class from classpath. InvocationTargetException: startup failed:
[ERROR] General error during conversion: java.lang.UnsupportedOperationException
[ERROR]
[ERROR] java.lang.UnsupportedOperationException
[ERROR] 	at groovyjarjarasm.asm.ClassVisitor.visitNestMemberExperimental(ClassVisitor.java:248)
[ERROR] 	at groovyjarjarasm.asm.ClassReader.accept(ClassReader.java:651)
[ERROR] 	at groovyjarjarasm.asm.ClassReader.accept(ClassReader.java:391)

**Comment by vimal4david** [comment]
Relates to this Groovy [issue](https://issues.apache.org/jira/browse/GROOVY-8727)

**Comment by hazendaz** [comment]
Requires groovy 2.5.3 and gmavenplus 1.6.2.  Currently both are pending release.

**Comment by vimal4david** [comment]
The build is failing because Travis CI is using Maven version 3.5.3. I have raised a [PR](https://github.com/travis-ci/travis-cookbooks/pull/997) in Travis CI to update there Maven version to 3.5.4

**Comment by hazendaz** [comment]
We use the maven wrapper so travis ci doesnt need bumped, although the doesnt hurt.  For this project look in the .mvn folder for the wrapper properties file and bump to 3.5.4 there.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
Closed via #88 

I have opened a new issue though against jdk11 on one unit test #90
