### ISSUE TITLE
Is there a way to configure an accepted number of errors in order to introduce spotbugs into existing projects

### ISSUE THREAD

**Issue by ottlinger** [spotbugs/spotbugs-maven-plugin#804]
When I use spotbugs for the first time on an existing codebase I expect it to find bugs/errors/warnings.

Is there a way to configure the maven plugin to accept a certain number of errors and fail the build if that number is exceeded?

After I checked the docs I thought about [failThreshold](https://spotbugs.github.io/spotbugs-maven-plugin/check-mojo.html#failThreshold), but this parameter is already used for something else.

Do you see value in an addition of an <allowedErrorsThreshold> configuration option that allows to migrate to spotbugs and integrate it into projects and fails the build only if that number is exceeded. A warning could be issued if the total bug count is lower that the configured threshold?

WDYT?

**Comment by hazendaz** [comment]
maxAllowedViolations?

See https://github.com/spotbugs/spotbugs-maven-plugin/pull/85/

**Comment by ottlinger** [comment]
> maxAllowedViolations?
> 
> See #85

Thanks, that is exactly what I was looking for!
