### ISSUE TITLE
Release 3.1.7

### ISSUE THREAD

**Issue by guw** [spotbugs/spotbugs-maven-plugin#83]
Spotbugs 3.1.7 is out with fix for Java 11. A new release of the Maven plug-in providing
https://github.com/spotbugs/spotbugs/issues/711 would be good.

**Comment by hazendaz** [comment]
This is being worked.  I'd prefer we can also build with jdk 11 because the underlying plugin is built on groovy and it's not yet fully working on jdk11.  See my fork travis ci builds.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
Requires groovy 2.5.3 and gmavenplus 1.6.2.  Currently both are pending release.

**Comment by hazendaz** [comment]
Releasing to central now.  This will be available in about 10 minutes and will show up in the index in next 1 to 2 hours.
