### ISSUE TITLE
Plugin tries to fetch latest snapshot version

### ISSUE THREAD

**Issue by anuragagarwal561994** [spotbugs/spotbugs-maven-plugin#830]
We are using snapshot pinning version so that different users can work on different snapshot version before a final version is released.

But when using spotbug plugin it fetches the latest version of the snapshot while the specific version is mentioned in the pom.xml leading to failures when changes are not compatible.

Disabling the plugin solves the issue.

**Comment by hazendaz** [comment]
Not sure I follow.  Are you using spotbugs snapshot?

**Comment by anuragagarwal561994** [comment]
No I am not using the snapshot version what do I mean by here is that if I am using a timestamped version of a snapshot dependency like 4.127-20240621.201418-5 then the plugin tries to fetch the latest snapshot version, is it intended by the maven plugin lifecycle or something that can be corrected?

**Comment by hazendaz** [comment]
You should never be doing that.  That is used by maven's metadata.  If you want to use snapshots then just use -SNAPSHOT.  The poms themselves will always have the snapshot in them as those timestamps are just meta data.

See metadata https://oss.sonatype.org/content/repositories/snapshots/com/github/spotbugs/spotbugs-maven-plugin/maven-metadata.xml file.  Also see that all poms regardless of their timestamp don't refer to the timestamp but rather snapshot.  Only reason you may possibly want a stuck snapshot is if something in latest build is broken but that is generally not a good idea.

Most often here you don't even need the snapshot.  Just override the spotbugs version instead.  The releases done here mostly don't change behaviour so you generally can run for example spotbugs 4.8.6 using the spotbugs-maven-plugin 4.8.5.0

**Comment by anuragagarwal561994** [comment]
So I am not using the snapshot version for spotbugs or the its maven plugin, but some other dependency. But the plugin is updating the dependency.

The reason why I am doing this is because, we have a project A and multiple people wants to work on this.

Then we have a project B which uses project A as a dependency.

What we thought of was to use the timestamped version in the respective branches and finally we release Project A and Project B uses the release version of Project A, otherwise it uses the timestamp snapshot version instead.

**Comment by hazendaz** [comment]
fundamentally that isn't how maven works.  you either have snapshots (throughout regardless of a timestamp) or you have a release.  It seems you are mixing concepts here and this has nothing to do with this plugin.  I'm not sure how I can help you here in regards.  It might be worth taking a look at maven docs - https://maven.apache.org/guides/getting-started/

**Comment by anuragagarwal561994** [comment]
So I have solved my issue with a different approach, but just wanted to check why would the plugin here create the issue.

Just to re-iterate, let me narrate what is happening here, I have a dependency:
```
<dependency>
    <groupId>com.example></groupId>
    <artifactId>artifact</artifactId>
    <version>4.127-20240621.201418-5</version>
</dependency>
```

The latest snapshot version available in the repository is `4.127-20240621.214430-7`

While compiling correct dependency `4.127-20240621.201418-5` is picked but when the spotbugs maven plugin runs or even though it is skipped, metadata of `4.127-20240621.214430-7` is fetched.

Usually when packaging the application into a jar, lets say using a shade plugin it refereces this dependency as `4.127-SNAPSHOT.jar` which is nothing but the soft link of `4.127-20240621.201418-5.jar` during the compile phase but when it hits this plugin, it becomes soft link of `4.127-20240621.214430-7.jar` and breaks the re-producibility of my final jar created.

That is mainly the issue, that why this happens.

**Comment by hazendaz** [comment]
AFAIK I don't believe maven should be used that way. I've never seen such a usage and it is overly complex for no real reason.  Snapshots are meant to be temporary and not something to be used like that.  Just use SNAPSHOT and if you really need pinned variations of a snapshot then release more frequently so versions are properly pinned.

I cannot answer why spotbugs plugin in any way affects that but it would likely not be the only one.  Not all plugins work off maven resolution for reporting purposes, but many do including this plugin does which uses maven transfer jars which themselves are deprecated.  That probably has something to do with it.  I think you would be far better asking these questions though over at maven user mailing list to get more broad feedback on your use case along with any pointers on what might be the issue.

[maven-mailing-lists](https://maven.apache.org/mailing-lists.html)

**Comment by hazendaz** [comment]
closing as invalid usage of maven and if concern of issue with maven, check with maven as this plugin doesn't manage how maven works.
