### ISSUE TITLE
outputDirectory default value is invalid.

### ISSUE THREAD

**Issue by dylan-tao** [spotbugs/spotbugs-maven-plugin#850]
> See
> 
> ```
>     /**
>      * Location where generated html will be created.
>      *
>      */
>     @Parameter(defaultValue = '${project.reporting.outputDirectory}', required = true)
>     File outputDirectory
> ```

please

> closing as this is already present in support.
> 
> See
> 
> ```
>     /**
>      * Location where generated html will be created.
>      *
>      */
>     @Parameter(defaultValue = '${project.reporting.outputDirectory}', required = true)
>     File outputDirectory
> ```
@hazendaz 
version: 4.8.6.2
Please test, the configuration item has been invalid, the default generated report is wrong under target, it should be in the site directory, and the above ${project.reporting.outputDirectory} is invalid.

_Originally posted by @dylan-tao in https://github.com/spotbugs/spotbugs-maven-plugin/issues/673#issuecomment-2260369051_

**Comment by hazendaz** [comment]
Believe #807 fixed that but not released yet.

**Comment by dylan-tao** [comment]
> Believe #807 fixed that but not released yet.

When to release？ @hazendaz

**Comment by hazendaz** [comment]
couple weeks or so.

**Comment by hazendaz** [comment]
Release 4.8.6.3 to support this.

**Comment by dylan-tao** [comment]
> Release 4.8.6.3 to support this.

thanks! 😊 🎉
