### ISSUE TITLE
Java 17 is required to build

### ISSUE THREAD

**Issue by elharo** [spotbugs/spotbugs-maven-plugin#931]
[ERROR] Rule 4: org.apache.maven.enforcer.rules.version.RequireJavaVersion failed with message:
[ERROR] Detected JDK version 11.0.16-1 (JAVA_HOME=/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home) is not in the allowed range [17,18),[21,22),[23,24),[24,25).
[ERROR] Rule 5: org.apache.maven.enforcer.rules.version.RequireMavenVersion failed with message:
[ERROR] Please upgrade maven and configure 'M2_HOME'.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To

However, the README says

"Java 11+ is required to build the project.  Java 8+ is required for spotbugs analysis."

Should we update the README or fix the enforcer rule?

**Comment by elharo** [comment]
The enforcer rule comes from the parent pom. Might be time to break that dependency,

**Comment by hazendaz** [comment]
Fixed the readme.  Some of the plugins moved onto requiring java 17 in the parent pom used, missed updating that there.  Readme now reflects java 17 or better to build.  Thank you for catching that.
