### ISSUE TITLE
Links to spotbugs website broken

### ISSUE THREAD

**Issue by kwin** [spotbugs/spotbugs-maven-plugin#94]
In https://spotbugs.github.io/spotbugs-maven-plugin/ there is still links to the no longer existing website at SourceForge. Those should be fixed to point to the new location at github.
Source: https://github.com/spotbugs/spotbugs-maven-plugin/blob/spotbugs/src/site/apt/index.apt.vm

**Comment by hazendaz** [comment]
@kwin Can you raise a PR to fix the broken link issues?

**Comment by hazendaz** [comment]
#102 Fixes this issue.
