### ISSUE TITLE
Make outputSpotbugsFile configurable

### ISSUE THREAD

**Issue by mkozioro** [spotbugs/spotbugs-maven-plugin#96]
Hi,

Would it be possible to make outputSpotbugsFileName configurable? I've got couple of old, annoying and unmaintained tool at my company, which is required by our management to collect report from findbugs. It has hardcoded findbugs output file name as findbugsXml.xml. We would like to switch to spotbugs, but I'm not even going to force my company to force 3rd party company to fix their tooling and add support for spotbugs.

Could you consider making output report name configurable? (instead of spotbugsXml.xml). I would be happy to provide PR (adding parameter spotbugsXmlOutputFileName or outputSpotbugsFileName) for that.

Best regards,
Michal

**Comment by hazendaz** [comment]
@mkozioro Sorry for delay...if you raise a pull request for this freature, I'll merge it in.  The more people using spotbugs the better as findbugs on all fronts has been abandoned at this point and you are otherwise missing out on all the greatness of jdk8+ support ;)

**Comment by massdosage** [comment]
We're also interested in this feature. We have a Jenkins installation that has the FindBugs Jenkins plugin for displaying reports. Unfortunately this Jenkins doesn't have the Warnings plugin that supports SpotBugs so if we want to move to SpotBugs but still be able to generate reports in Jenkins we need to be able to modify the output filename to be findbugsXml.xml. We're hoping the XML format is still compatible enough that the older Jenkins plugin can render it. The longer term plan is to move to a newer Jenkins version which has the Warnings plugin but this would be really useful in the mean time. We'll take a look at raising a PR, I had a quick look at the code and it looks relatively straightforward.

**Comment by cmathiesen** [comment]
I've raised the PR ^ that hopefully fixes this issue, any feedback or comments is appreciated :)
