### ISSUE TITLE
Tag / source missing for 3.1.9

### ISSUE THREAD

**Issue by zman0900** [spotbugs/spotbugs-maven-plugin#97]
The maven site for this plugin and maven central say the latest version is 3.1.9, but there are no changes here after the 3.1.8 tag.  This is still the correct repo according to: https://spotbugs.github.io/spotbugs-maven-plugin/scm.html  Where can I find source code for 3.1.9?

**Comment by hazendaz** [comment]
repo has been tagged with 3.1.9, closing.
